import {useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {useAction,useResource,write} from "../data/hooks";
import {readOnce} from "../data/imperative";
import {PageFrame} from "../components/PageFrame";
import {WORKBOOK_AFFECTS,downloadWorkbook,type InstanceSummary,type TemplateSummary} from "../components/workbooks/model";
import type {LibraryDepartment,LibraryShelf,LibraryCatalog} from "../components/mastering/libraryTypes";
export function WorkbooksPage(){
 const run=useAction(),navigate=useNavigate(),[archived,setArchived]=useState(false),[templateId,setTemplateId]=useState(""),[title,setTitle]=useState(""),[error,setError]=useState("");
 const [placement,setPlacement]=useState<InstanceSummary|null>(null),[department,setDepartment]=useState(""),[shelf,setShelf]=useState("");
 const [projectType,setProjectType]=useState(""),[projectId,setProjectId]=useState("");
 const templates=useResource<TemplateSummary[]>("/workbooks/templates"),instances=useResource<InstanceSummary[]>(`/workbooks/instances${archived?"?archived=1":""}`);
 const departments=useResource<LibraryDepartment[]>(placement?"/book-library/departments":null),shelves=useResource<LibraryShelf[]>(placement?"/book-library/shelves":null);
 const projects=useResource<{id:number;name:string}[]>(projectType?`/workbooks/projects/${projectType}`:null);
 async function create(){const result=await run(()=>write.post<{id:number}>("/workbooks/instances",{template_id:Number(templateId),title:title.trim(),project_type:projectType||null,project_id:projectId?Number(projectId):null}),{affects:WORKBOOK_AFFECTS,retry:false});if(result)navigate(`/workbooks/${result.id}`);}
 async function importFile(file:File|undefined){if(!file)return;setError("");try{if(file.size>4*1024*1024)throw new Error("Файл шаблона или тетради должен быть до 4 МБ");const data=JSON.parse(await file.text());await run(()=>write.post(data.format==="soyman-workbook"?"/workbooks/templates":"/workbooks/import",data),{affects:WORKBOOK_AFFECTS,retry:false});}catch(e){setError((e as Error).message);}}
 async function place(){if(!placement)return;try{const result=await readOnce<LibraryCatalog>(`/book-library/books?source_type=workbook&source_id=${placement.id}&include_unplaced=1`);const book=result.books[0];if(!book)throw new Error("Тетрадь не найдена");const saved=await run(()=>write.put(`/book-library/books/${book.id}`,{department_id:department?Number(department):null,shelf_id:shelf?Number(shelf):null}),{affects:WORKBOOK_AFFECTS});if(saved!==undefined)setPlacement(null);}catch(e){setError((e as Error).message);}}
 return <PageFrame title="Тетради и шаблоны"><Link to="/mastering">← Библиотека</Link><p>Тетради появляются у книг после явного связывания. На полку их можно поставить отдельно.</p>{error&&<p role="alert">{error}</p>}{(templates.error||instances.error)&&<p role="alert">{templates.error||instances.error}</p>}
 <div className="card stack"><h2>Новая тетрадь</h2><label>Шаблон<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Выбрать</option>{templates.data?.filter(t=>!t.archived_at).map(t=><option value={t.id} key={t.id}>{t.title} · {t.version}</option>)}</select></label><label>Название<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Связанный проект<select value={projectType} onChange={e=>{setProjectType(e.target.value);setProjectId("");}}><option value="">Без проекта</option><option value="campaign">Кампания</option><option value="setting">Сеттинг</option><option value="adventure">Приключение</option></select></label>{projectType&&<select aria-label="Проект" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Выбрать проект</option>{projects.data?.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>}<button className="primary" disabled={!title.trim()||!templateId||!!projectType&&!projectId} onClick={()=>void create()}>Создать</button></div>
 <label>Импорт шаблона или тетради (.json)<input type="file" accept=".json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value="";}}/></label><p><a href="/workbook-example.json" download>Пример универсального шаблона</a> · <a href="/workbook-author-guide.md" download>Инструкция автору</a></p>
 <h2>Мои экземпляры</h2><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Показать архив</label>{instances.data?.map(i=><div className="card row" key={i.id}><Link to={`/workbooks/${i.id}`}>{i.title}</Link><span>{i.template_title} · {i.template_version}</span><button onClick={()=>{void run(()=>write.put(`/workbooks/instances/${i.id}`,{revision:i.revision,archived:!archived}),{affects:WORKBOOK_AFFECTS});}}>{archived?"Восстановить":"В архив"}</button>{!archived&&<button onClick={()=>{setPlacement(i);setDepartment("");setShelf("");}}>Размещение на полке</button>}</div>)}
 {placement&&<div className="card stack"><h3>{placement.title}</h3><label>Подраздел<select value={department} onChange={e=>{setDepartment(e.target.value);setShelf("");}}><option value="">Без подраздела</option>{departments.data?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Полка<select value={shelf} onChange={e=>setShelf(e.target.value)}><option value="">Без полки</option>{shelves.data?.filter(s=>s.department_id===(department?Number(department):null)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button onClick={()=>void place()}>Сохранить размещение</button><button onClick={()=>setPlacement(null)}>Отмена</button></div>}
 <details><summary>Версии шаблонов и архив</summary>{templates.data?.map(t=><div className="card row" key={t.id}><span>{t.title} · {t.version}{t.archived_at?" · архив":""}</span><button onClick={async()=>{const data=await readOnce(`/workbooks/templates/${t.id}`);downloadWorkbook(`${t.template_key}-v${t.version}.json`,JSON.stringify(data,null,2));}}>Скачать</button><button onClick={()=>{void run(()=>write.put(`/workbooks/templates/${t.id}/archive`,{archived:!t.archived_at}),{affects:WORKBOOK_AFFECTS});}}>{t.archived_at?"Восстановить":"В архив"}</button></div>)}</details></PageFrame>;
}
