import path from 'node:path';
import { fileURLToPath } from 'node:url';
import react from '../client/node_modules/@vitejs/plugin-react/dist/index.js';
import { readFile } from 'node:fs/promises';
const root = path.dirname(fileURLToPath(import.meta.url));
const client = path.resolve(root, '../client');
const transport = path.join(client, 'src/api/client.ts').replaceAll('\\', '/');
export default {
  root: path.join(root, 'app'),
  publicDir: path.join(client, 'public'),
  plugins: [{ name: 'oneshot-local-transport', enforce: 'pre', resolveId(source, importer) {
    if (!importer || !source.startsWith('.')) return;
    const resolved = path.resolve(path.dirname(importer.split('?')[0]), source).replaceAll('\\', '/');
    if (resolved === transport || resolved + '.ts' === transport) return path.join(root, 'app/transport.ts');
  }, configureServer(server) {
    server.middlewares.use('/standalone-template.html', async (_req, res) => {
      try { const html = await readFile(path.join(root, 'generated/standalone-template.html'), 'utf8'); res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); }
      catch (e) { res.statusCode = 500; res.end('Standalone build failed'); server.config.logger.error(String(e)); }
    });
    // Development only: index.html references ./manifest.webmanifest, but the
    // source lives in app/pwa (outside publicDir). Without this the dev
    // server answers the manifest request with the SPA HTML fallback and the
    // browser reports an invalid manifest. Production is untouched: build-pwa
    // copies the manifest into app-dist.
    server.middlewares.use('/manifest.webmanifest', async (_req, res) => {
      try { const manifest = await readFile(path.join(root, 'app/pwa/manifest.webmanifest'), 'utf8'); res.setHeader('Content-Type', 'application/manifest+json'); res.end(manifest); }
      catch (e) { res.statusCode = 500; res.end('Manifest read failed'); server.config.logger.error(String(e)); }
    });
    // Development only: manifest icons are generated by build-pwa into
    // app-dist/icons; here they are resized from the same artwork on request.
    server.middlewares.use('/icons', async (req, res, next) => {
      const size = Number((req.url || '').match(/^\/icon-(192|512)\.png/)?.[1]);
      if (!size) return next();
      try { const { default: sharp } = await import('../server/node_modules/sharp/dist/index.mjs'); res.setHeader('Content-Type', 'image/png'); res.end(await sharp(path.join(client, 'public/app-icon.png')).resize(size, size, { fit: 'cover' }).png().toBuffer()); }
      catch (e) { res.statusCode = 500; res.end('Icon build failed'); server.config.logger.error(String(e)); }
    });
    // Development only: managed catalog release built by run-app from
    // private/catalog.json into catalog/. Without it the SPA fallback answers
    // catalog/manifest.json with HTML and the first creation fails.
    server.middlewares.use('/catalog', async (req, res, next) => {
      const name = decodeURIComponent((req.url || '').split('?')[0].replace(/^\//, ''));
      if (!/^[\w.-]+\.json$/.test(name)) return next();
      try { const data = await readFile(path.join(root, 'catalog', name)); res.setHeader('Content-Type', 'application/json'); res.setHeader('Cache-Control', 'no-store'); res.end(data); }
      catch { res.statusCode = 404; res.end('Catalog release not built'); }
    });
    // Development only; private catalog is never copied to app-dist.
    server.middlewares.use('/__local/catalog', async (req, res) => {
      if (req.method !== 'GET') { res.statusCode = 405; res.end(); return; }
      try { const data = await readFile(path.join(root, 'private/catalog.json')); res.setHeader('Content-Type', 'application/json'); res.setHeader('Cache-Control', 'no-store'); res.end(data); }
      catch { res.statusCode = 404; res.end('Local catalog not prepared'); }
    });
  } }, react()],
  resolve: { alias: {
    '@shared': path.resolve(root, '../shared/src'),
    'react': path.join(client, 'node_modules/react'),
    'react-dom': path.join(client, 'node_modules/react-dom'),
    'react-router-dom': path.join(client, 'node_modules/react-router-dom'),
    '@tanstack/react-query': path.join(client, 'node_modules/@tanstack/react-query'),
    // QR for the sync pairing screen reuses the main client's qrcode.react;
    // no new dependency, no external service (see run-app shared build note).
    'qrcode.react': path.join(client, 'node_modules/qrcode.react/lib/esm/index.js'),
  }, dedupe: ['react', 'react-dom', '@tanstack/react-query'] },
  server: { host: '127.0.0.1', port: 4318, strictPort: true, fs: { allow: [path.resolve(root, '..')] } },
  build: { outDir: path.join(root, 'app-dist'), emptyOutDir: true },
};
